name: Deploy to Nekoweb

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
       
      - name: "Deploy 2 Nekoweb"
        uses: indiefellas/deploy2nekoweb@main
        with: 
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: "hoshiai.space"
          nekoweb-username: "meowbyte"
          directory: "."